name: Release notes
on:
  push:
    tags:
      - "*"
jobs:
  create-shasums:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
